// automatically generated by the FlatBuffers compiler, do not modify

#ifndef FLATBUFFERS_GENERATED_TYPES_FBS_HW1_H_
#define FLATBUFFERS_GENERATED_TYPES_FBS_HW1_H_

#include "flatbuffers/flatbuffers.h"


namespace fbs {
namespace hw1 {

struct StringPayload;
struct BinaryPayload;

enum Payload {
  Payload_NONE = 0,
  Payload_StringPayload = 1,
  Payload_BinaryPayload = 2
};

inline const char **EnumNamesPayload() {
  static const char *names[] = { "NONE", "StringPayload", "BinaryPayload", nullptr };
  return names;
}

inline const char *EnumNamePayload(Payload e) { return EnumNamesPayload()[static_cast<int>(e)]; }

inline bool VerifyPayload(flatbuffers::Verifier &verifier, const void *union_obj, Payload type);

struct StringPayload FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  const flatbuffers::String *content() const { return GetPointer<const flatbuffers::String *>(4); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, 4 /* content */) &&
           verifier.Verify(content()) &&
           verifier.EndTable();
  }
};

struct StringPayloadBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_content(flatbuffers::Offset<flatbuffers::String> content) { fbb_.AddOffset(4, content); }
  StringPayloadBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  StringPayloadBuilder &operator=(const StringPayloadBuilder &);
  flatbuffers::Offset<StringPayload> Finish() {
    auto o = flatbuffers::Offset<StringPayload>(fbb_.EndTable(start_, 1));
    return o;
  }
};

inline flatbuffers::Offset<StringPayload> CreateStringPayload(flatbuffers::FlatBufferBuilder &_fbb,
   flatbuffers::Offset<flatbuffers::String> content = 0) {
  StringPayloadBuilder builder_(_fbb);
  builder_.add_content(content);
  return builder_.Finish();
}

struct BinaryPayload FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  const flatbuffers::Vector<int8_t> *content() const { return GetPointer<const flatbuffers::Vector<int8_t> *>(4); }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<flatbuffers::uoffset_t>(verifier, 4 /* content */) &&
           verifier.Verify(content()) &&
           verifier.EndTable();
  }
};

struct BinaryPayloadBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_content(flatbuffers::Offset<flatbuffers::Vector<int8_t>> content) { fbb_.AddOffset(4, content); }
  BinaryPayloadBuilder(flatbuffers::FlatBufferBuilder &_fbb) : fbb_(_fbb) { start_ = fbb_.StartTable(); }
  BinaryPayloadBuilder &operator=(const BinaryPayloadBuilder &);
  flatbuffers::Offset<BinaryPayload> Finish() {
    auto o = flatbuffers::Offset<BinaryPayload>(fbb_.EndTable(start_, 1));
    return o;
  }
};

inline flatbuffers::Offset<BinaryPayload> CreateBinaryPayload(flatbuffers::FlatBufferBuilder &_fbb,
   flatbuffers::Offset<flatbuffers::Vector<int8_t>> content = 0) {
  BinaryPayloadBuilder builder_(_fbb);
  builder_.add_content(content);
  return builder_.Finish();
}

inline bool VerifyPayload(flatbuffers::Verifier &verifier, const void *union_obj, Payload type) {
  switch (type) {
    case Payload_NONE: return true;
    case Payload_StringPayload: return verifier.VerifyTable(reinterpret_cast<const StringPayload *>(union_obj));
    case Payload_BinaryPayload: return verifier.VerifyTable(reinterpret_cast<const BinaryPayload *>(union_obj));
    default: return false;
  }
}

}  // namespace hw1
}  // namespace fbs

#endif  // FLATBUFFERS_GENERATED_TYPES_FBS_HW1_H_
